services:
  - type: static
    name: permapiola-web
    buildCommand: npm run build
    publishPath: dist/permapiola-web/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
